In [41]:
import pandas as pd
import numpy as num

In [42]:
print(pd.__version__)

2.2.3

In [43]:
# Read the CSV file
df = pd.read_csv("Car_Dataset.csv", encoding_errors='ignore')

In [44]:
df.shape

(23906, 17)

In [45]:
df.head()

,SR.No,Purchase_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,1,C_CND_000001,01/02/2022,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÃ‚Â Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,2,C_CND_000002,01/02/2022,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÃ‚Â Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,3,C_CND_000003,01/02/2022,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,4,C_CND_000004,01/02/2022,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,5,C_CND_000005,01/02/2022,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÃ‚Â Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville

In [46]:
df.describe()

              SR.No  Annual Income     Price ($)
count  23906.000000   2.390600e+04  23906.000000
mean   11953.500000   8.308403e+05  28090.247846
std     6901.212104   7.200064e+05  14788.687608
min        1.000000   1.008000e+04   1200.000000
25%     5977.250000   3.860000e+05  18001.000000
50%    11953.500000   7.350000e+05  23000.000000
75%    17929.750000   1.175750e+06  34000.000000
max    23906.000000   1.120000e+07  85800.000000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SR.No          23906 non-null  int64
 1   Purchase_id    23906 non-null  object
 2   Date           23906 non-null  object
 3   Customer Name  23905 non-null  object
 4   Gender         23906 non-null  object
 5   Annual Income  23906 non-null  int64
 6   Dealer_Name    23906 non-null  object
 7   Company        23906 non-null  object
 8   Model          23906 non-null  object
 9   Engine         23906 non-null  object
 10  Transmission   23906 non-null  object
 11  Color          23906 non-null  object
 12  Price ($)      23906 non-null  int64
 13  Dealer_No      23906 non-null  object
 14  Body Style     23906 non-null  object
 15  Phone          23906 non-null  object
 16  Dealer_Region  23906 non-null  object
dtypes: int64(3), object(14)
memory usage: 3.1+ MB

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.isnull().sum()

SR.No            0
Purchase_id      0
Date             0
Customer Name    1
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

In [50]:
df.dropna(inplace=True)

In [51]:
df.isnull().sum()

SR.No            0
Purchase_id      0
Date             0
Customer Name    0
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

In [52]:
df.dtypes

SR.No             int64
Purchase_id      object
Date             object
Customer Name    object
Gender           object
Annual Income     int64
Dealer_Name      object
Company          object
Model            object
Engine           object
Transmission     object
Color            object
Price ($)         int64
Dealer_No        object
Body Style       object
Phone            object
Dealer_Region    object
dtype: object